const CONSTANTS = {
  MODULE_NAME: "animated-tile-states",

  BEHAVIORS: {
    STILL: "still",
    LOOP: "loop",
    ONCE_NEXT: "once-next",
    ONCE_PREVIOUS: "once-previous",
    ONCE_PREVIOUS_ACTIVE: "once-previous-active",
    ONCE_SPECIFIC: "once-specific"
  },
  START: {
    END: "end",
    MID: "mid",
    PREV: "prev"
  },
  END: {
    NEXT: "next",
    MID: "middle",
    END: "end"
  }
}

CONSTANTS.SOCKET_NAME = `module.${CONSTANTS.MODULE_NAME}`;

CONSTANTS.FLAG_KEYS = {
  PREVIOUS_STATE: "previousState",
  CURRENT_STATE: "currentState",
  QUEUED_STATE: "queuedState",
  UPDATED: "updated",
  STATES: "states",
  SOURCE: "src",
  FRAMES: "frames",
  FPS: "fps",
  DELEGATED_TILES: "delegatedTiles",
}

CONSTANTS.FLAGS = `flags.${CONSTANTS.MODULE_NAME}`;
CONSTANTS.PREVIOUS_STATE_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.PREVIOUS_STATE}`;
CONSTANTS.CURRENT_STATE_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.CURRENT_STATE}`;
CONSTANTS.QUEUED_STATE_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.QUEUED_STATE}`;
CONSTANTS.UPDATED_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.UPDATED}`;
CONSTANTS.STATES_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.STATES}`;
CONSTANTS.SOURCE_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.SOURCE}`;
CONSTANTS.FRAMES_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.FRAMES}`;
CONSTANTS.FPS_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.FPS}`;
CONSTANTS.DELEGATED_TILES_FLAG = `flags.${CONSTANTS.MODULE_NAME}.${CONSTANTS.FLAG_KEYS.DELEGATED_TILES}`;

CONSTANTS.TRANSLATED_BEHAVIORS = {
  [CONSTANTS.BEHAVIORS.STILL]: "Still",
  [CONSTANTS.BEHAVIORS.LOOP]: "Loop",
  [CONSTANTS.BEHAVIORS.ONCE_NEXT]: "Once, then next state",
  [CONSTANTS.BEHAVIORS.ONCE_PREVIOUS]: "Once, then previous state",
  [CONSTANTS.BEHAVIORS.ONCE_PREVIOUS_ACTIVE]: "Once, then previous active state",
  [CONSTANTS.BEHAVIORS.ONCE_SPECIFIC]: "Once, then specific state",
}

export default CONSTANTS;
